project:
  type: website
  output-dir: docs

website:
  title: "BCB520 Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Elsa7364
format:
  html:
    css: styles.css
    theme: cosmo
